# Generated by Django 3.0.10 on 2020-10-03 13:57

from django.db import migrations, models
import notes.notebook.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20201003_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=notes.notebook.models.get_photo_path),
        ),
    ]
