# Generated by Django 3.0.10 on 2020-09-19 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_default_categories(apps, schema_editor):
    Type = apps.get_model('notebook', 'Type')
    Type.objects.create(full_name='Flowers')
    Type.objects.create(full_name='Food recipes')


class Migration(migrations.Migration):
    dependencies = [('notebook', '0002_auto_20200919_1612'), ]

    operations = [migrations.RunPython(add_default_categories), ]
