# Generated by Django 3.0.10 on 2020-09-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_add_default_notes_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['full_name'], 'verbose_name': 'Note type', 'verbose_name_plural': 'Note types'},
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
